#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

exec s6-setuidgid agpsn python3 "${APP_DIR}/sabnzbd/SABnzbd.py" --browser 0 --server 0.0.0.0:8080 --config-file "${CONFIG_DIR}/sabnzbd.ini" ${ARGS}
