#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=${PUID}
PGID=${PGID}
UMASK=${UMASK}
TZ=${TZ}
ARGS=${ARGS}
VERSION=$(cat /app/sabnzbd/app_version)
----------------------------------------------------------------------
"

if [[ ! "${PUID}" -eq 0 ]] && [[ ! "${PGID}" -eq 0 ]]; then
    echo "Executing usermod..."
    mkdir "/tmp/temphome"
    usermod -d "/tmp/temphome" agpsn
    usermod -o -u "${PUID}" agpsn
    usermod -d "${CONFIG_DIR}" agpsn
    rm -rf "/tmp/temphome"
    groupmod -o -g "${PGID}" agpsn
else
    echo "Running as root is not supported, please fix your PUID and PGID!"
    exit 1
fi

echo "Applying permissions to ${CONFIG_DIR}"
chmod 755 -R "${CONFIG_DIR}"
chown agpsn:agpsn "${CONFIG_DIR}"
